import Head from 'next/head'
import { PRODUCT_QUERY } from '@/lib/query'
import { useQuery } from 'urql'
import Product from "../components/Product";
import { Gallery } from "../styles/Gallery";



export default function Home() {
//fetch products from strapi
  const [results] = useQuery({query: PRODUCT_QUERY})
  console.log(results)
  const {data, fetching, error} = results;

    //check for the data coming in
    if(fetching) return <p>Loading...</p>
    if(error) return <p>Oh no...{error.message}</p>
    console.log(data);
    const products = data.products.data;


  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Gallery>
          {/* {fetching && <Skeleton />} */}
          {products.map((product) => (
            <Product key={product.attributes.slug} product={product} />
          ))}
        </Gallery>
      </main>
    </>
  );
}
